### PR TITLE
Don't use a hidden file for the config on linux

### LINKED ISSUE #1851: man page gives incorrect path to config
### What happened?

The man page(s) says the path to the config is `$HOME/.local/share/input-leap/.input-leap.conf`. However after this didn't work, and doing an `strace`, it is actually looking for `$HOME/.local/share/InputLeap/.input-leap.conf`

### Version

v2.4.0

### Git commit hash (if applicable)

_No response_

### If applicable, where did you install Input Leap from?

fedora

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

_No response_

### What OS versions are you using?

fedora 39

### Relevant log output

_No response_

### Any other information

_No response_

### PR DESCRIPTION
**Pull request by sithlord48**
Unify `USR_CONFIG_NAME` and `SYS_CONFIG_NAME` into one new `CONFIG_NAME`. This moves the USER based config from `$HOME/.local/share/input-leap/.input-leap.conf` -> `$HOME/.config/Inputleap/input-leap.conf`

Fixes #1851  by correcting the path in the manual.

### CODE REVIEW

**Review by shymega — COMMENTED** [review]
Wait, why is the config file hidden?

**Comment by sithlord48** [comment]
> Wait, why is the config file hidden?

not sure my config doesn't have that file at all on my server I was just updating based upon the user report

**Comment by shymega** [comment]
Yeah, we should patch that in the codebase, the config file shouldn't be hidden. But we'll need to add a migration flow as well, so that we rename the `.input-leap.conf` - like how we do with the `Debauchee` migration flow.

**Comment by sithlord48** [comment]
I'll look into it and update this MR after .

**Comment by shymega** [comment]
Looks okay, but let's update the PR title/description, and add migration for the old path in the codebase, so users have a hassle-free experience. Or we can do that in a later PR.

cc:/ @p12tic

**Comment by whot** [comment]
fwiw, config should go into `XDG_CONFIG_HOME` (aka `$HOME/.config`, the user-equivalent to `/etc`), you're putting it into `XDG_DATA_DIR` (aka `$HOME/.local/share`, the user-equivalent to `/usr/local/share`).

I strongly recommend against using `XDG_DATA_DIR` for config, it'll be confusing and inconsistent with other apps out there.

**Comment by sithlord48** [comment]
Done should use ~/.config/InputLeap/input-leap.conf on linux

**Comment by whot** [comment]
possibly stupid idea, feel free to ignore: default.conf as fallback, otherwise $hostname.conf so you can store multiple configurations in the same (synced-across machines) config directory.

**Comment by sithlord48** [comment]
No. When I tried the file was created for me with no intervention

File: src/lib/inputleap/ServerApp.h [hunk 1]
```diff
@@ -118,11 +118,9 @@ class ServerApp : public App {
 
 // configuration file name
 #if SYSAPI_WIN32
-#define USR_CONFIG_NAME "input-leap.sgc"
-#define SYS_CONFIG_NAME "input-leap.sgc"
+#define CONFIG_NAME "input-leap.sgc"
```
Comment (shymega) [inline src/lib/inputleap/ServerApp.h:121]: This should be split into a separate PR. Currently the PR is for 'not using hidden files for config on Linux' - but this change affects win32.

File: src/lib/inputleap/ServerApp.h [hunk 2]
```diff
@@ -118,11 +118,9 @@ class ServerApp : public App {
...
 #elif SYSAPI_UNIX
-#define USR_CONFIG_NAME ".input-leap.conf"
-#define SYS_CONFIG_NAME "input-leap.conf"
+#define CONFIG_NAME "input-leap.conf"
```
Comment (shymega) [inline src/lib/inputleap/ServerApp.h:123]: Not sure if we should keep a `SYS` config name...

**Review by shymega — CHANGES_REQUESTED** [review]
Just a couple of nitpicks.

**Comment by shymega** [comment]
> No. When I tried the file was created for me with no intervention
> […](#)
> On Tue, May 14, 2024, 3:04 AM Povilas Kanapickas ***@***.***> wrote: I don't see migration code, is there any?

I also want to check this is migrated OK on Windows.

**Comment by sithlord48** [comment]
> > No. When I tried the file was created for me with no intervention
> > […](#)
> > On Tue, May 14, 2024, 3:04 AM Povilas Kanapickas _**@**_.***> wrote: I don't see migration code, is there any?
> 
> I also want to check this is migrated OK on Windows.

Nothing changed on windows to migrate..

File: src/lib/inputleap/ServerApp.h (hunk 2 above)
Comment (sithlord48) [reply src/lib/inputleap/ServerApp.h:123]: Both names are the same so no i don't think we need to store a `sys` config name

File: src/lib/inputleap/ServerApp.h (hunk 1 above)
Comment (shymega) [reply src/lib/inputleap/ServerApp.h:121]: OK, thanks for the clarification.

File: src/lib/inputleap/ServerApp.h (hunk 2 above)
Comment (shymega) [reply src/lib/inputleap/ServerApp.h:123]: OK, thanks for the clarification.

**Comment by shymega** [comment]
OK, @p12tic approved this PR, so I'll go ahead and merge.

**Review by shymega — APPROVED** [review]
LGTM.

**Comment by p12tic** [comment]
@shymega 

FYI I didn't approve the PR and my comment "I don't see migration code, is there any?" hasn't been addressed. Now we have a regression where user config is being lost.
