### PR TITLE
ei: fix the scroll events

### LINKED ISSUE #1840: Mouse wheel scroll jumps are huge with Wayland
### What happened?

When I run the IL server on Wayland (and the client on X11 -- although I don't know if this is particularly relevant to this issue -- I don't have Wayland running machine to test as a client) the mouse's scroll wheel events are huge on the client.

That is, when I move the scroll wheel on the mouse just one _notch_ the scrolling jump on the application on the client is huge, as if the wheel were moved much much more than it was.

### Version

From Git HEAD or commit (specify below)

### Git commit hash (if applicable)

c5bb9dca

### If applicable, where did you install Input Leap from?

https://copr.fedorainfracloud.org/coprs/ofourdan/input-leap-ei-enabled/

### What OSes are you seeing the problem on? (Check all that apply)

Linux

### If applicable, are you using Wayland or X11?

Wayland on the server and X11 on the client.

### What OS versions are you using?

Fedora 39 on the server and Fedora 38 on the client.

### Relevant log output

_No response_

### Any other information

_No response_

### PR DESCRIPTION
**Pull request by whot**
We may get scroll events or scroll discrete events and both may be in fractions of a single logical scroll event. Handle this by mapping 10 pixels to one wheel click (that's what mutter/gtk do too) and otherwise keeping the remainder around in the device for the next scroll event.

Note that we're always sending things through as wheel, so on the client side we only ever call ei_device_scroll_discrete().

In theory, our pointer and keyboard device may be the same ei device, so let's assume we have a user data on all of them and free them during cleanup - that way we don't need complicated checks of which devices are the same device.

Fixes #1840

cc @brianjmurrell, @prahal

---
Note that there's a remaining issue: mutter seems to be sending both normal and discrete scroll events so the scrolling is still twice what it should be. That seems to be a bug in mutter somewhere, not in input-leap.

### CODE REVIEW

**Comment by hunterzero99** [comment]
I gave the branch a try, on a Windows client I not get no movement with small mouse wheel scrolls, and with a very agressive scroll I may get a very small amount of movement in certain windows (Google Chrome)

**Comment by shymega** [comment]
> I gave the branch a try, on a Windows client I not get no movement with small mouse wheel scrolls, and with a very agressive scroll I may get a very small amount of movement in certain windows (Google Chrome). It might be a client issue if you're not seeing it on other builds. I'm running an outdated version of barrier on this client due to there being no Windows build without debugging enabled.

Ideally, you should be using the _same codebase_ on both clients. We can't promise Barrier will work with Input Leap mixed forever.

However, the changes in this PR only apply to systems using `libei`.

**Comment by hunterzero99** [comment]
> Ideally, you should be using the _same codebase_ on both clients. We can't promise Barrier will work with Input Leap mixed forever.

Understood, I just ran [this debug build](https://github.com/input-leap/input-leap/actions/runs/7927164889/job/21643093472) from this commit on my Windows client and I get the same result.

**Comment by whot** [comment]
>  on a Windows client I not get no movement with small mouse wheel scrolls, and with a very agressive scroll I may get a very small amount of movement in certain windows (Google Chrome). It might be a client issue if you're not seeing it on other builds

can you run the server with logging please and tell me what it says for scroll events? it should log the deltas it's sending so we can narrow down where the issue is.

File: src/lib/platform/EiScreen.cpp [hunk 1]
```diff
@@ -85,11 +94,25 @@ EiScreen::~EiScreen()
     events_->set_buffer(nullptr);
     events_->remove_handler(EventType::SYSTEM, events_->getSystemTarget());
 
-    ei_device_unref(ei_pointer_);
-    ei_device_unref(ei_keyboard_);
-    ei_device_unref(ei_abs_);
+    if (ei_pointer_) {
+        free(ei_device_get_user_data(ei_pointer_));
+        ei_device_set_user_data(ei_pointer_, NULL);
```
Comment (sithlord48) [inline src/lib/platform/EiScreen.cpp:99]: Any reason to use  `NULL` over `nullptr` here ?

Comment (whot) [reply src/lib/platform/EiScreen.cpp]: oops, no, just decades of C programming coming through :) good catch, fixed, thanks.

**Comment by whot** [comment]
> on a Windows client I not get no movement with small mouse wheel scrolls, and with a very agressive scroll I may get a very small amount of movement in certain windows (Google Chrome)

Found the bug, switching to draft so this one doesn't get merged accidentally.

**Comment by whot** [comment]
Ready now, I got the units wrong so it worked between ei->ei but not between ei->other.

Note that we still get a duplicate scroll event from mutter so we scroll twice the amount we should but that's a mutter bug.

**Comment by hunterzero99** [comment]
Latest update is working great with a Windows client, thank you for the hard work!

**Review by sithlord48 — APPROVED** [review]

**Comment by prahal** [comment]
Confirmed PR working on an IL Wayland server to an IL Wayland client (both Gnome Shell 45.3).

I also confirm the double scroll event on the client from the IL server scroll, that is a page up is 10 scroll up when using the mouse on the Gnome Shell 45.3 IL server while scrolling 5 times from the server to the IL client is one page up.
Is there a bug already open on mutter gnome gitlab for this issue?

To me, this PR is ready to be merged.

**Comment by shymega** [comment]
Merging. I wonder if this affects KWin too, not just Mutter.

**Comment by whot** [comment]
> I wonder if this affects KWin too, not just Mutter.

Mutter has a specific way of event processing, it converts libinput events to clutter events and those clutter events later pass through the main compositor and eventually get sent to the wayland client or, in our case, via libei to us. For historical reasons mutter gets the smooth scroll event and the discrete scroll event from libinput and processes them as two separate events. That's fine with Wayland because the protocol stacks them together as one logical event, depending on the client version. The ei protocol explicitly states either/or so sending both events results in duplicate events on the client side.

KWin *may* have a similar bug if it has a similar internal implementation but either way, this is very much not a libei/input-leap issue.

Thanks heaps for all the merges!

**Comment by whot** [comment]
mutter PR is now filed as [mutter!3637](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3637)
